# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_na_character <- function(x) {
    .Call('emil_has_na_character', PACKAGE = 'emil', x)
}

has_na_complex <- function(x) {
    .Call('emil_has_na_complex', PACKAGE = 'emil', x)
}

has_na_expression <- function(x) {
    .Call('emil_has_na_expression', PACKAGE = 'emil', x)
}

has_na_numeric <- function(x) {
    .Call('emil_has_na_numeric', PACKAGE = 'emil', x)
}

is_constant_character <- function(x, na_rm) {
    .Call('emil_is_constant_character', PACKAGE = 'emil', x, na_rm)
}

is_constant_complex <- function(x, na_rm) {
    .Call('emil_is_constant_complex', PACKAGE = 'emil', x, na_rm)
}

is_constant_numeric <- function(x, na_rm) {
    .Call('emil_is_constant_numeric', PACKAGE = 'emil', x, na_rm)
}

